name: Performance benchmarking

on:
  push:
    branches: [ develop ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.PERFORMANCE_BENCHMARK_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Avaiga/taipy-integration-testing/actions/workflows/benchmark.yml/dispatches \
          -d '{"ref": "develop"}'
