name: Trigger Milestones
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Run Milestones demos
        run: gh workflow run run-all-demos.yml -f user-to-notify=$GITHUB_ACTOR -R Avaiga/milestones
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_OTHER_ACTION }}
