name: Trigger Milestones
on:
  push:
    branches: [ develop, feature/#21-trigger-taipy-rest ]
jobs:
  trigger:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Run tests on milestones
        run: gh workflow run run-all-demos.yml -f user-to-notify=$GITHUB_ACTOR -R Avaiga/milestones
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_OTHER_ACTION }}

      - name: Run tests on taipy-airflow
        run: gh workflow run test.yml -f user-to-notify=$GITHUB_ACTOR -R Avaiga/taipy-airflow
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_OTHER_ACTION }}

      - name: Run tests on taipy-rest
        run: gh workflow run test.yml -f user-to-notify=$GITHUB_ACTOR -R Avaiga/taipy-rest
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_OTHER_ACTION }}
